In [16]:
import pandas as pd
import nemo
import nemo.collections.nlp as nemo_nlp

In [17]:
nmt_model = nemo_nlp.models.machine_translation.MTEncDecModel.from_pretrained(model_name="nmt_es_en_transformer12x2").cuda()

[NeMo I 2021-06-14 15:47:25 cloud:56] Found existing object C:\Users\hapir\.cache\torch\NeMo\NeMo_1.0.0\nmt_es_en_transformer12x2\42fbff52240a2c8cb1127d2a97201f6d\nmt_es_en_transformer12x2.nemo.
[NeMo I 2021-06-14 15:47:25 cloud:62] Re-using file from: C:\Users\hapir\.cache\torch\NeMo\NeMo_1.0.0\nmt_es_en_transformer12x2\42fbff52240a2c8cb1127d2a97201f6d\nmt_es_en_transformer12x2.nemo
[NeMo I 2021-06-14 15:47:25 common:675] Instantiating model from pre-trained checkpoint
[NeMo I 2021-06-14 15:47:40 tokenizer_utils:129] Getting YouTokenToMeTokenizer with model: C:\Users\hapir\AppData\Local\Temp\tmpkycn3a0z\tokenizer.32000.BPE.model.
[NeMo I 2021-06-14 15:47:40 tokenizer_utils:129] Getting YouTokenToMeTokenizer with model: C:\Users\hapir\AppData\Local\Temp\tmpkycn3a0z\tokenizer.32000.BPE.model.

[NeMo W 2021-06-14 15:47:40 modelPT:137] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    src_file_name: /raid/sharded_tarfiles_60_even/batches.tokens.16000._OP_1..302_CL_.tar
    tgt_file_name: /raid/sharded_tarfiles_60_even/batches.tokens.16000._OP_1..302_CL_.tar
    tokens_in_batch: 16000
    clean: true
    max_seq_length: 512
    cache_ids: false
    cache_data_per_node: false
    use_cache: false
    shuffle: true
    num_samples: -1
    drop_last: false
    pin_memory: false
    num_workers: 8
    load_from_cached_dataset: false
    reverse_lang_direction: true
    load_from_tarred_dataset: true
    metadata_path: /raid/sharded_tarfiles_60_even/metadata.json
    tar_shuffle_n: 100

[NeMo W 2021-06-14 15:47:40 modelPT:144] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    src_file_name: /raid/newstest2012-es-en.clean.tok.src
    tgt_file_name: /raid/newstest2012-es-en.clean.tok.ref
    tokens_in_batch: 512
    clean: false
    max_seq_length: 512
    cache_ids: false
    cache_data_per_node: false
    use_cache: false
    shuffle: false
    num_samples: -1
    drop_last: false
    pin_memory: false
    num_workers: 8
    load_from_cached_dataset: false
    reverse_lang_direction: false
    load_from_tarred_dataset: false
    metadata_path: null
    tar_shuffle_n: 100

[NeMo W 2021-06-14 15:47:40 modelPT:151] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    src_file_name: /raid/newstest2013-es-en.clean.tok.src
    tgt_file_name: /raid/newstest2013-es-en.clean.tok.ref
    tokens_in_batch: 512
    clean: false
    max_seq_length: 512
    cache_ids: false
    cache_data_per_node: false
    use_cache: false
    shuffle: false
    num_samples: -1
    drop_last: false
    pin_memory: false
    num_workers: 8
    load_from_cached_dataset: false
    reverse_lang_direction: false
    load_from_tarred_dataset: false
    metadata_path: null
    tar_shuffle_n: 100

[NeMo W 2021-06-14 15:47:40 modelPT:1198] World size can only be set by PyTorch Lightning Trainer.

[NeMo I 2021-06-14 15:47:43 modelPT:434] Model MTEncDecModel was successfully restored from C:\Users\hapir\.cache\torch\NeMo\NeMo_1.0.0\nmt_es_en_transformer12x2\42fbff52240a2c8cb1127d2a97201f6d\nmt_es_en_transformer12x2.nemo.

In [18]:
all_words_es = pd.read_csv('ALL_WORDS_ES.csv')

In [19]:
all_words_es

,Unnamed: 0,SOURCE,ARTICULO,WORDS,TRANSLATE,SENTENCES,READ,HEAR,WRITE,TALK,STATUS
0,0,BLONDYNA_NEW_ES,NaN,Hola,Czesc,NaN,NaN,NaN,NaN,NaN,NaN
1,1,BLONDYNA_NEW_ES,NaN,Yo soy,Jestem,NaN,NaN,NaN,NaN,NaN,NaN
2,2,BLONDYNA_NEW_ES,Un,marinero,marynarz,NaN,NaN,NaN,NaN,NaN,NaN
3,3,BLONDYNA_NEW_ES,Un,viajero,podroznik,NaN,NaN,NaN,NaN,NaN,NaN
4,4,BLONDYNA_NEW_ES,Un,capitan,kapitan,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5091,4995,NaN,NaN,arreglo,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5092,4996,NaN,NaN,magistrado,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5093,4997,NaN,NaN,notables,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5094,4998,NaN,NaN,registros,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5095,4999,NaN,NaN,jugó,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
for ind in all_words_es.index:
    translate = nmt_model.translate([all_words_es['WORDS'][ind]])
    all_words_es['TRANSLATE'][ind] = translate[0]

[NeMo W 2021-06-14 15:48:18 nemo_logging:349] <ipython-input-20-3bf900779630>:3: SettingWithCopyWarning:
    A value is trying to be set on a copy of a slice from a DataFrame

    See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
      all_words_es['TRANSLATE'][ind] = translate[0]

In [21]:
all_words_es

,Unnamed: 0,SOURCE,ARTICULO,WORDS,TRANSLATE,SENTENCES,READ,HEAR,WRITE,TALK,STATUS
0,0,BLONDYNA_NEW_ES,NaN,Hola,Hello there,NaN,NaN,NaN,NaN,NaN,NaN
1,1,BLONDYNA_NEW_ES,NaN,Yo soy,I am,NaN,NaN,NaN,NaN,NaN,NaN
2,2,BLONDYNA_NEW_ES,Un,marinero,sailor,NaN,NaN,NaN,NaN,NaN,NaN
3,3,BLONDYNA_NEW_ES,Un,viajero,traveler,NaN,NaN,NaN,NaN,NaN,NaN
4,4,BLONDYNA_NEW_ES,Un,capitan,capitan,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5091,4995,NaN,NaN,arreglo,arrangement,NaN,NaN,NaN,NaN,NaN,NaN
5092,4996,NaN,NaN,magistrado,magistrate,NaN,NaN,NaN,NaN,NaN,NaN
5093,4997,NaN,NaN,notables,remarkable,NaN,NaN,NaN,NaN,NaN,NaN
5094,4998,NaN,NaN,registros,Records,NaN,NaN,NaN,NaN,NaN,NaN
5095,4999,NaN,NaN,jugó,he played,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
all_words_es.to_csv('ALL_WORDS_ES.csv')